version: '2'

networks:
  app-tier:
    driver: bridge

services:
  rabbitmq:
    image: 'bitnami/rabbitmq:latest'
    networks:
      - app-tier
    environment:
      - RABBITMQ_USERNAME=user
      - RABBITMQ_PASSWORD=bitnami
    ports:
      - '15672:15672'
      - '5672:5672'
  myapp:
    image: 'rabbitmq'
    networks:
      - app-tier
